CREATE TABLE IF NOT EXISTS orders (
  `id` SERIAL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `total` DECIMAL(10, 2) NOT NULL CHECK (total > 0),
  `status` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES users(`id`)
);